
services:
  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Berlin
    ports:
      - "3306:3306"
    healthcheck:
      test:
        - CMD-SHELL
        - /usr/bin/mysql
        - --silent
        - -e
        - "show databases;"
      interval: 1s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
      - TZ=Europe/Berlin
    secrets:
      - database_url

secrets:
  database_url:
    file: ./database_url.txt

volumes:
  db-data:

