
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-"user"}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-"pass"}
      POSTGRES_DB: ${DB_NAME:-"db"}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/pgdata"
      o: bind

