name: Run PostgreSQL with Docker Compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.0.0/docker-compose-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build and run services
      run: docker-compose up -d

    - name: Wait for PostgreSQL to be ready
      run: sleep 30

    - name: Run PostgreSQL query
      run: |
        docker-compose exec postgres psql -U myuser -d mydatabase -c "SELECT * FROM employees;"

    - name: Shut down services
      run: docker-compose down