name: PostgreSQL with Data Mount

on: [push,workflow_dispatch]

jobs:
  postgres-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydatabase
        options: >-
          --mount type=bind,source=${{ github.workspace }}/mounter,target=/var/lib/postgresql/data
        ports:
          - 5432:5432


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Wait for PostgreSQL to be ready
      run: sleep 30

    - name: Query Data
      run: |
        docker exec -i ${{ job.services.postgres.id }} psql -U myuser -d mydatabase -c "SELECT * FROM employees;"