name: Run PostgreSQL with Docker Compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "./docker-compose.yml"
        test-container: "postgres"
        test-command: "psql -U myuser -d mydatabase -c \"SELECT * FROM employees;\""

    - name: Shut down services
      run: docker-compose down