name: Run PostgreSQL with Docker Compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2' # the full version of `docker-compose` command



    - name: Build and run services
      run: docker-compose up -d

    - name: Wait for PostgreSQL to be ready
      run: sleep 40

    - name: Run PostgreSQL query
      run: |
        docker ps

    - name: Shut down services
      run: docker-compose down