name: Restore Postgres from Backup

on: 
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  restore-postgres:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in the repository (for debugging)
      run: ls -R

    - name: Create Docker volume
      run: docker volume create restored_pgdata

    - name: Restore Postgres data from backup
      run: |
        docker run --rm -v restored_pgdata:/volume -v $(pwd)/backup:/backup busybox tar xzvf /backup/postgres_volume_backup.tar.gz -C /volume

    - name: Start Postgres with Restored Volume
      run: |
        docker run -d --name github_postgres_container \
          -e POSTGRES_DB=my_sample_db \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=mysecretpassword \
          -p 5432:5432 \
          --health-cmd="pg_isready -U postgres" \
          --health-interval=10s \
          --health-timeout=5s \
          --health-retries=5 \
          -v restored_pgdata:/var/lib/postgresql/data \
          postgres:latest

    - name: Verify Data
      run: |
        docker exec github_postgres_container psql -U postgres -d my_sample_db -c "SELECT * FROM employees;"