name: Restore Postgres from Backup

on: 
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  restore-postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: my_sample_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
        ports:
          - 5432:5432
        options: > 
          --health-cmd="pg_isready -U postgres" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create Docker volume
      run: docker volume create restored_pgdata

    - name: Restore Postgres data from backup
      run: |
        docker run --rm -v restored_pgdata:/volume -v $(pwd)/backups:/backup busybox tar xzvf /backup/postgres_volume_backup.tar.gz -C /volume

    - name: Start Postgres with Restored Volume
      run: |
        docker run -d --name github_postgres_container -e POSTGRES_PASSWORD=mysecretpassword -v restored_pgdata:/var/lib/postgresql/data postgres

    - name: Verify Data
      run: |
        docker exec -it github_postgres_container psql -U postgres -d my_sample_db -c "SELECT * FROM employees;"